; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; Find the sum of all the even-valued terms in the sequence which do not exceed four million.

(defn fib-even-terms-sum [first second]
  "recursively calulates a fibonacci sequence
  adding all even-valued terms while the even terms are <= four million"
  (loop [f first s second sum-of-even 0]
    (if (> s 4000000)
      sum-of-even
      (recur (identity s) (+ f s) (if (even? s) (+ s sum-of-even) (identity sum-of-even))))))

(println (fib-even-terms-sum 1 2))